import { Inter } from 'next/font/google'
import HeaderLayout from '@/layouts/HeaderLayout';
import "@/styles/globals.scss"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Descuentify - Recompensas a clientes fieles',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <HeaderLayout />
        {children}
      </body>
    </html>
  )
}
