import { Inter } from 'next/font/google'
import styles from '@/styles/general.module.scss';
import HeaderLayout from '@/layouts/HeaderLayout';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Descuentify - Recompensas a clientes fieles',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <HeaderLayout />
        {children}
      </body>
    </html>
  )
}
